name: morning
on:
  workflow_dispatch:
  schedule:
  - cron:  '03 12 * * *'

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to zxr

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      LC_ID: ${{ secrets.LC_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      USER_ID:  ${{ secrets.USER_ID }}
      GRADUATION: ${{ secrets.GRADUATION_DATE }}
